#!/usr/bin/env php

<?php 

require_once __DIR__ . '/vendor/autoload.php';

use Dice\RollCommand;
use Symfony\Component\Console\Application;

$app = new Application();

$app->add(new RollCommand());

$app->run();
